### ISSUE TITLE
About the C++ version

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [UkcheolShin/Noise-AwareCameraExposureControl#1]
Excellent work！ I saw in your paper that there is a C++ version of the code. Where can I get the code?

**Comment by UkcheolShin** [comment]
Sorry for the late response. Currently, the c ++ code is not well organized and also intertwined with other development code. I will upload it when it is cleaned up later. But if you need it immediately, please send me an email at shinwc159@gmail.com. then, I will send the current version code.

**Comment by wangyuanbiubiubiu** [comment]
Thank you, I have implemented the C++ version according to your MATLAB version

**Comment by singhsonam2509** [comment]
Hi,

It is really an interesting paper.
As Matlab license is not free, I would be glad if you could provide the C++ version.

**Comment by UkcheolShin** [comment]
I uploaded the C++ version code. The cpp code includes the C++ version of the image quality assessment metric.
I hope it is helpful to you! 
Thank you.

**Comment by singhsonam2509** [comment]
Thank you very much!
